import type { Metadata } from 'next';
import { Geist, Geist_Mono, Press_Start_2P } from 'next/font/google'; // Add Press_Start_2P
import './globals.css';

// Configure Geist Sans
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// Configure Geist Mono
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Configure Press Start 2P
const pressStart2P = Press_Start_2P({
  variable: '--font-press-start', // Custom CSS variable
  subsets: ['latin'],
  weight: '400', // Press Start 2P only has 400 weight
  display: 'swap', // Optional: Improves loading behavior
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pressStart2P.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
